### ISSUE TITLE
Blank Screen After reflashing

### ISSUE THREAD

**Issue by chanyork** [seeul8er/RepPanel_ESP32#15]
Hello,  I believe I have a HWV1.  After reflashing my RepPanel screen is blank.  Please help.

**Comment by chanyork** [comment]
by the way the flash was successful.  it become blank once i erase the firmware.  and after that reflash nothing on screen

**Comment by chanyork** [comment]
![IMG_7328](https://user-images.githubusercontent.com/28833849/221737099-4e1d990f-bad6-43b4-a6a9-cbe37be404c5.jpg)
Attached is my board .

**Comment by seeul8er** [comment]
You are using v2 Hardware. I will contact you via email, since this is the git for the HWv1 release :)
