### ISSUE TITLE
FT6X36: Error reading from device: ERROR

### ISSUE THREAD

**Issue by tunip** [seeul8er/RepPanel_ESP32#3]
Hi,

flashed the newest version (1.0.1) to my ESP32 (https://www.amazon.de/gp/product/B07PG923ZK/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)

Checked wires, should be fine. If I start the ESP32 I see the following message:

```
[15:32:35]I (210) ILI9488: ILI9488 initialization.
[15:32:36]I (510) ILI9488: Enabling backlight.
[15:32:36]I (510) FT6X36: Found touch panel controller
[15:32:36]E (510) FT6X36: Error reading from device: ERROR
[15:32:36]I (510) FT6X36: 	Device ID: 0x00
[15:32:36]I (520) FT6X36: 	Chip ID: 0x00
[15:32:36]I (520) FT6X36: 	Device mode: 0x00
[15:32:36]I (530) FT6X36: 	Firmware ID: 0x00
[15:32:36]I (530) FT6X36: 	Release code: 0x00
```

Any idea what can I check?

Display is showing only a white screen after start.

PS: Checked another ESP32 (LOLIN D32) same error with white screen.

**Comment by seeul8er** [comment]
Should be a wiring/config issue.

Are you using the ER-TFT?
Can you post your wiring?
Did you compile yourself or use the provided image?

**Comment by tunip** [comment]
OK, rewired it again.

Yes, it is a ER-TFTM035-6 display.

Wiring is exactly from the README.md:
![IMG_0772](https://user-images.githubusercontent.com/11404472/83973707-80806a80-a8e8-11ea-9c03-b723090384f6.jpg)
![IMG_0770](https://user-images.githubusercontent.com/11404472/83973598-f801ca00-a8e7-11ea-9ad8-00e82faae965.jpg)
![IMG_0771](https://user-images.githubusercontent.com/11404472/83973601-f932f700-a8e7-11ea-9586-d13c724adc40.jpg)

Did a try with the provided image and now I also tried a compile by my self. Both are the same issue.

Will try different cables. Maybe one of them is faulty.

**Comment by seeul8er** [comment]
Can you post an image of the back of your TFT board? From your pictures it looks like you got one that is in "8080 16-bit Interface" configuration. The ESP32/RepPanel only supports SPI displays as for now.
You need a board with 4 Wire SPI (3 wire should work as well but untested) and the capacitive touch screen (for pre-build images). Font chip is not required.
See [https://www.buydisplay.com/download/manual/ER-TFTM035-6_Datasheet.pdf](https://www.buydisplay.com/download/manual/ER-TFTM035-6_Datasheet.pdf) Section 4.3

However, you should be able to "transform/hack" your board to be in 4 wire config. That would require you to solder/desolder some jumpers and resistors. Not sure that is worth the trouble.

**Comment by tunip** [comment]
Back of the TFT board. Did not know of the different variants of the ER-TFTM035-6. Buyed it from buydisplay eBay shop. Ordered the right one now. Lets wait a few weeks.

![IMG_0773](https://user-images.githubusercontent.com/11404472/83975788-05be4c00-a8f6-11ea-96e5-050761da435f.jpg)

In the package, there was also an Arduino Shield.

**Comment by seeul8er** [comment]
Yes, definitley not the SPI version. The yellow ribbon cable is also missing the capacitive touch panel chip. Found it on ebay as well. Ebay is a lot more confusing than their dedicated website.

Sorry for that, I'll make sure to update the README so that others do not make the same mistake.
I'll close this issue for now. Do not hesitate to open a new one when there are problems with the new board.
