### ISSUE TITLE
how to resize to 320x240 ili9341

### ISSUE THREAD

**Issue by minhngoc123** [seeul8er/RepPanel_ESP32#5]
![118910056_367033494297947_7642871273519694239_n](https://user-images.githubusercontent.com/70738064/92200291-af848900-eea3-11ea-8102-8bb59ecc94a6.jpg)
i use ili9341 i confi into esp-idfto 320x240 but it to big ,thanks you

**Comment by seeul8er** [comment]
You need to know your way around the LVGL library and then rewrite big portions of the code to adjust the scale of all elements. There is no out of the box solution. I do not belive that 320x240 will deliver a good user experiance.
